location: eastus
name: frontend
resourceGroup: rg-todo-platform
type: Microsoft.App/containerApps
properties:
  environmentId: /subscriptions/74d57c28-6ef3-4b79-b0fa-663db8274da4/resourceGroups/rg-todo-platform/providers/Microsoft.App/managedEnvironments/cae-todo-platform
  configuration:
    activeRevisionsMode: Single
    dapr:
      enabled: true
      appId: frontend
      appPort: 3000
      appProtocol: http
    ingress:
      external: true
      allowInsecure: false
      targetPort: 3000
      transport: auto
    registries:
      - server: acrtodoplatform.azurecr.io
        username: acrtodoplatform
        passwordSecretRef: acr-password
    secrets:
      - name: acr-password
        value: "G4PXgo9FmlAEb3gGIbkNXbRAgg1fUdsf2tIlO3zSV17yE0SxFQ5nJQQJ99CBACYeBjFEqg7NAAACAZCR6ZQ5"
      - name: openrouter-api-key
        value: "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"
      - name: better-auth-secret
        value: "qTVmp/NQbah0P6sSMdU2WMCBjLQwdfOR/BFOHtU6yHA="
      - name: db-url
        value: "postgresql://neondb_owner:npg_ViUF4kTjQc0u@ep-empty-night-a1f62zum-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - name: auth-secret
        value: "CScmNpQrZezguV+hM/nAmWrZpp428klCIAhic+R4OKo="
  template:
    containers:
      - image: acrtodoplatform.azurecr.io/frontend:latest
        name: frontend
        resources:
          cpu: 0.5
          memory: 1Gi
        env:
          - name: PORT
            value: "3000"
          - name: DATABASE_URL
            secretRef: db-url
          - name: NODE_ENV
            value: "production"
          - name: AUTH_SECRET
            secretRef: auth-secret
          - name: OPENROUTER_API_KEY
            secretRef: openrouter-api-key
          - name: BETTER_AUTH_SECRET
            secretRef: better-auth-secret
          - name: OPENAI_BASE_URL
            value: "https://openrouter.ai/api/v1"