apiVersion: v1
kind: Service
metadata:
  name: recurring-service
  namespace: todo-platform
  labels:
    app: recurring-service
spec:
  type: ClusterIP
  selector:
    app: recurring-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
