apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
